# Generated by Django 3.2.15 on 2022-09-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='tables',
            field=models.IntegerField(null=True),
        ),
    ]
