# Generated by Django 3.2.15 on 2022-09-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20220906_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='booking',
            name='time',
            field=models.TimeField(max_length=200, null=True),
        ),
    ]
