# Generated by Django 3.2.15 on 2022-09-06 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20220906_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='datetime',
        ),
    ]
