# Generated by Django 3.2.15 on 2022-09-07 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_auto_20220907_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='customer',
        ),
    ]
