# Generated by Django 3.2.15 on 2022-09-08 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0015_booking_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='lastName',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='lastName',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='deliveryinfo',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='deliveryinfo',
            old_name='lastName',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='deliveryinfo',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
    ]
