# Generated by Django 3.2.15 on 2022-09-08 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0017_auto_20220908_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user_permissions',
        ),
    ]
