# Generated by Django 3.2.15 on 2022-09-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0024_alter_booking_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='open_times',
            new_name='open_times_weekdays',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='open_times_weekends',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
