# Generated by Django 3.2.15 on 2022-09-19 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0026_auto_20220918_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryinfo',
            old_name='date_ordered',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='date_ordered',
            new_name='created_on',
        ),
    ]
